# Generated by Django 4.2 on 2023-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zadacha', models.CharField(max_length=128, verbose_name='Задача')),
                ('theme', models.CharField(max_length=128, verbose_name='Тема')),
                ('slozhnost', models.PositiveIntegerField(default=1, verbose_name='Сложность')),
                ('vopros', models.PositiveIntegerField(default=1, verbose_name='Вопрос №')),
            ],
        ),
    ]
