# Generated by Django 4.2 on 2023-05-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_options_remove_task_slozhnost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koli', models.PositiveIntegerField(default=1, verbose_name='Количество заданий')),
            ],
            options={
                'verbose_name': 'Количество заданий',
                'verbose_name_plural': 'Количество заданий',
            },
        ),
    ]
