# Generated by Django 4.2 on 2023-05-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kol',
            options={'verbose_name': 'Количество', 'verbose_name_plural': 'Количество'},
        ),
        migrations.AddField(
            model_name='kol',
            name='foli',
            field=models.TextField(default='1'),
        ),
    ]
